import { buildStateSchema, compileGraph } from "./compiler.ts";
import {
  LangGraphAbstraction,
  StatePropertyDefinition,
  NodeRegistry,
} from "./types.ts";

// ==========================================
// 1. STATE: Theme Analyzer and Article Writer
// ==========================================
const stateDef: Record<string, StatePropertyDefinition> = {
  // User input in standard message format
  messages: {
    type: "array",
    items: { type: "object", required: false },
    reducerStrategy: "append",
    required: true,
  },
  // Structured object generated by the LLM Analyzer
  analysis: {
    type: "object",
    reducerStrategy: "overwrite",
    required: false,
    properties: {
      is_valid: { type: "boolean", required: true },
      category: {
        type: "enum",
        options: ["science", "technology", "art", "other"],
        required: true,
      },
      difficulty: { type: "number", required: true },
    },
  },
  // Content generated by the Writer
  content: {
    type: "string",
    reducerStrategy: "overwrite",
    required: false,
  },
};

// ==========================================
// 2. THE GRAPH (JSON from Database)
// ==========================================
const abstraction: LangGraphAbstraction = {
  stateSchema: stateDef,
  nodes: [
    {
      id: "node_analyzer",
      name: "Theme Analyzer",
      type: "llm",
      config: {
        model: "qwen3:8b",
        temperature: 0.1,
        systemPrompt:
          "You are an expert analyzing themes. The user will give you a topic and you must evaluate it strictly.",
        structuredOutput: stateDef.analysis,
        outputKey: "analysis",
      },
    },
    {
      id: "node_writer",
      name: "Specialist Writer",
      type: "llm",
      config: {
        model: "qwen3:8b",
        temperature: 0.7,
        systemPrompt:
          "You are an expert writer. Write a 3-line paragraph about the topic proposed by the user.",
        outputKey: "content",
      },
    },
    {
      id: "node_reject",
      name: "Rejector",
      type: "compute",
      config: { pluginId: "reject_handler" },
    },
  ],
  edges: [
    {
      id: "e1",
      source: "start",
      target: "node_analyzer",
      isConditional: false,
    },
    {
      id: "e2",
      source: "node_analyzer",
      target: "node_reject",
      isConditional: true,
      condition: {
        field: "analysis.is_valid",
        operator: "equals",
        value: false,
      },
    },
    {
      id: "e3",
      source: "node_analyzer",
      target: "node_reject",
      isConditional: true,
      condition: {
        field: "analysis.difficulty",
        operator: "greater_than",
        value: 8,
      },
    },
    {
      id: "e4",
      source: "node_analyzer",
      target: "node_writer",
      isConditional: true,
      condition: {
        field: "analysis.is_valid",
        operator: "equals",
        value: true,
      },
    },
    { id: "e5", source: "node_writer", target: "end", isConditional: false },
    { id: "e6", source: "node_reject", target: "end", isConditional: false },
  ],
};

// ==========================================
// 3. PLUGINS (Custom compute logic)
// ==========================================
const registry: NodeRegistry = {
  reject_handler: async (state, _config) => {
    console.log(`[Rejector] The topic was rejected by previous analysis.`);
    return {
      content:
        "The article could not be written because the topic does not meet the criteria (invalid or too difficult).",
    };
  },
};

// ==========================================
// 4. COMPILER EXECUTION
// ==========================================
async function main() {
  console.log("Compiling complex architecture...");
  const schema = buildStateSchema(stateDef);
  const fakeMicrokernel = {
    getTool: (name: string) => ({ name, description: "Fake tool" }),
  };
  const app = compileGraph(abstraction, schema, registry, fakeMicrokernel);

  const initialState = {
    messages: [
      { role: "user", content: "Quantum physics in modern computing" },
    ],
    analysis: undefined,
    content: "",
  };

  const finalState = (await app.invoke(initialState)) as Record<string, any>;

  console.log("\n==================================");
  console.log("FINAL STATE:");
  console.log(
    "Structured Analysis:",
    JSON.stringify(finalState.analysis, null, 2),
  );
  console.log("\nGenerated Content:\n" + finalState.content);
  console.log("==================================");
}

if (import.meta.main) {
  main().catch(console.error);
}
